@startuml
'https://plantuml.com/class-diagram

!include ../services/WeaponService.puml

package controllers {
    class WeaponController {
        - service: WeaponService
        ----
        + List<Weapon> getAll()
        + Weapon getById(UUID id)
        + Weapon save(Weapon weapon)
        + Weapon update(UUID id, Weapon weapon)
        + Weapon Delete(UUID id)
    }
}

WeaponController::service --> WeaponService

@enduml