@startuml
'https://plantuml.com/class-diagram

!include EntityService.puml
!include ../repositories/CharacterMongoRepository.puml

package services {
    class CharacterService implements EntityService {
        - repository: CharacterMongoRepository
    }
}


CharacterService::repository ---> CharacterMongoRepository

@enduml