@startuml
'https://plantuml.com/class-diagram

!include EntityService.puml
!include ../repositories/LocationMongoRepository.puml

package services {
    class LocationService implements EntityService {
        - repository: LocationMongoRepository
    }
}

LocationService::repository ---> LocationMongoRepository

@enduml