@startuml
'https://plantuml.com/class-diagram

!include ../services/LocationService.puml

package controllers {
    class LocationController {
        - service: LocationService
        ----
        + List<Location> getAll()
        + Location getById(UUID id)
        + Location save(Location location)
        + Location update(UUID id, Location location)
        + Location Delete(UUID id)
    }
}

LocationController::service --> LocationService

@enduml